default: &default
  adapter: postgresql
  encoding: unicode
  host: movies-db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: movies_development


test:
  <<: *default
  database: movies_test
