# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1166a279dda4ebabf4a636b192f9b5ce3f761ccbc832d4da3f708317b1371d014f4392765fc1a75744d597fb657eadbcce9819e82b131f0b8aee0a51735ccf71

test:
  secret_key_base: d3184cbabb7e1041d6b1c6d8336b6b5c89b6949e401ea8edf55c405a81e0ae7b9d51892b7a2569e7a770ad00022939385c17ab49aa758a9cb84771c377614eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
